apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k3s-fake-store
spec:
  provider:
    fake:
      data:
      - key: "argocd-helm-secret-string"
        value: "Very very secret string"
        version: "v1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k3s-fake-store
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
  data:
  - secretKey: secret-string
    remoteRef:
      key: argocd-helm-secret-string
      version: v1
