apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-example-project
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/ptisma/argocd-helm'
  destinations:
  - namespace: 'argocd-helm'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-example-project
  destination:
    namespace: argocd-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts  # contains application spec files
    repoURL: https://github.com/ptisma/argocd-helm
    targetRevision: main
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-server
  namespace: argocd # The namespace must match the namespace of your Argo CD instance
spec:
  project: argocd-example-project
  source:
    repoURL: https://github.com/ptisma/argocd-helm
    targetRevision: main
    path: charts/argocd-helm-server
    helm:
     valueFiles:
      - values-main.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-client
  namespace: argocd # The namespace must match the namespace of your Argo CD instance
spec:
  project: argocd-example-project
  source:
    repoURL: https://github.com/ptisma/argocd-helm
    targetRevision: main
    path: charts/argocd-helm-client
    helm:
     valueFiles:
      - values-main.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-helm
