apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: longhorn-system
spec:
  stripPrefix:
    prefixes:
      - /longhorn
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-stage"
    traefik.ingress.kubernetes.io/router.middlewares: "longhorn-system-stripprefix@kubernetescrd"
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "basic-auth"
  name: longhorn
  namespace: longhorn-system
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - ptisma.xyz
    - www.ptisma.xyz
    secretName: ptisma-xyz-tls
  rules:
  - host: ptisma.xyz
    http:
      paths:
        - pathType: Prefix
          path: "/longhorn"
          backend:
            service:
              name: longhorn-frontend
              port:
                number: 80
  - host: www.ptisma.xyz
    http:
      paths:
        - pathType: Prefix
          path: "/longhorn"
          backend:
            service:
              name: longhorn-frontend
              port:
                number: 80