apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-client
  namespace: argocd # The namespace must match the namespace of your Argo CD instance
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: argocd-example-project
  source:
    repoURL: https://github.com/ptisma/argocd-helm
    targetRevision: main
    path: charts/argocd-helm-client
    helm:
     valueFiles:
      - values-main.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-helm
    